#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Set correct hostnames for web servers
sudo hostnamectl set-hostname [STUDENT_ID]-lb-01
echo "[STUDENT_ID]-web-01" | sudo tee /etc/hostname > /dev/null
echo "[STUDENT_ID]-web-02" | sudo tee -a /etc/hostname > /dev/null
sudo sed -i '/127.0.1.1/s/$/ [STUDENT_ID]-web-01 [STUDENT_ID]-web-02/' /etc/hosts

# Restart HAProxy
sudo systemctl restart haproxy
