#!/usr/bin/env bash

# Configure Nginx so that its HTTP response contains
# a custom header

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Set correct hostnames for web servers (assuming STUDENT_ID is already defined somewhere)
hostname_web_01="[STUDENT_ID]-web-01"
hostname_web_02="[STUDENT_ID]-web-02"

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen http-in
    bind :80
    balance roundrobin
    server $hostname_web_01 54.167.59.25:80 check
    server $hostname_web_02 54.167.59.25:80 check
EOF

# Restart HAProxy
sudo service haproxy restart

