#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Holberton School"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/' /etc/nginx/nginx.conf
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
